//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitFrameworkNorthwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public int Id { get; set; }
        public string ReturnDetail { get; set; }
        public string CustomerId { get; set; }
    
        public virtual Returns Returns1 { get; set; }
        public virtual Returns Returns2 { get; set; }
    }
}
