//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitFrameworkNorthwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_heavy
    {
        public string ShipName { get; set; }
        public string ShipCity { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string CompanyName { get; set; }
    }
}
